### ISSUE TITLE
Readme link not working

### ISSUE THREAD

**Issue by phoce** [AMitchell-GitHub/GoogleSheetsDiscordBotv2#1]
The link in the readme section to the google site is not working, it just gives a 404 error. I have tried googling it and the link there also gives a 404.

**Comment by mitchellaidant** [comment]
Hmmm that’s odd. I just tested the link and it worked for me.

Try bit.ly/aidanssiteofstuffs

Let me know if that doesn't work either!

**Comment by phoce** [comment]
Same, page just displays the following.

404. That’s an error.

The requested URL was not found on this server. That’s all we know.

**Comment by mitchellaidant** [comment]
Try clearing your cache and cookies.

https://support.google.com/accounts/answer/32050?co=GENIE.Platform%3DDesktop&hl=en

Also try another browser / device if possible, because the issue is
probably on your end.

If that still doesn't work then I’ll do my best to send you the page so you
can open it on your computer.

Best of luck!

**Comment by phoce** [comment]
Still no luck. Cleared caches tried on 3 different devices. Safari, Firefox and Chrome and all give the 404 error.  No idea why it won't let me load the page.

**Comment by mitchellaidant** [comment]
Ahhh, sorry, I didn't have it set up to be shared with everyone. I had no
idea Google didn't do that by default lol. Should be all good now, sorry
for the trouble!

**Comment by phoce** [comment]
Thanks!
